# Generated by Django 6.0.4 on 2026-08-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('application_date', models.DateField()),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Interview', 'Interview'), ('Rejected', 'Rejected'), ('Offer', 'Offer'), ('Accepted', 'Accepted')], default='Applied', max_length=20)),
                ('job_url', models.URLField(blank=True)),
                ('salary', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
