# Generated by Django 6.0.4 on 2026-08-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_applicationstatushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
